server.host: 0.0.0.0
csp.script_src: ["'self' 'unsafe-eval' blob: https://*.pendo.io wss://*.pendo.io https://*.storage.googleapis.com https://feeds.elastic.co https://*.tile.openstreetmap.org"]
xpack.security.sameSiteCookies: None
xpack.security.authc.providers:
  basic.basic1:
    order: 0
  oidc.vdx:
    order: 1
    realm: vdx
    description: 'Log in with Vantage DX'
    icon: 'https://static.martellotech.com/icons/martello.png'
  token.token1:
    order: 2
    description: 'Log in with service-account token'  
vis_type_vega.enableExternalUrls: true
xpack.reporting.roles.enabled: false